# Generated by Django 5.1 on 2024-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_alter_products_options_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='intel', verbose_name='Imagen'),
        ),
    ]
