# Generated by Django 5.1 on 2024-10-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
