# Generated by Django 5.0.9 on 2024-12-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0008_accionafiladocausa_actividadesfce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('pundocumento', models.IntegerField(db_column='PunDocumento', primary_key=True, serialize=False)),
                ('pungrupo', models.IntegerField(blank=True, db_column='PunGrupo', null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('revision', models.IntegerField(blank=True, db_column='Revision', null=True)),
                ('vigencia', models.DateTimeField(blank=True, db_column='Vigencia', null=True)),
                ('linkpdf', models.CharField(blank=True, db_column='LinkPDF', max_length=150, null=True)),
                ('linkxls', models.CharField(blank=True, db_column='LinkXLS', max_length=150, null=True)),
                ('linkdoc', models.CharField(blank=True, db_column='LinkDOC', max_length=150, null=True)),
                ('linkplantilla', models.CharField(blank=True, db_column='LinkPlantilla', max_length=150, null=True)),
                ('borrado', models.IntegerField(blank=True, db_column='Borrado', null=True)),
            ],
            options={
                'db_table': 'Documentos',
                'managed': False,
            },
        ),
    ]
